name: Generate Extension Zip

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Create Zip file
      run: |
        zip extension.zip extension.js metadata.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: autokey-gnome-extension
        path: |
          extension.zip

    - name: Create Ubuntu Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Extension Release"
        files: |
          README.md
          extension.zip